namespace sprites.alphabet {
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="alphabet"
    export const alphabet25 = image.ofBuffer(hex``);
}
