namespace background {
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img01_logo1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img02_logo = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img03_heart1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img04_heart2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img05_eyes1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img06_eyes2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img07_eyes3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img08_eyes4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img09_butterfly1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img10_butterfly2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img11_cat2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img12_cat1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img13_dog1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img14_dog2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img15_floppy1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img17_smile = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img18_frown = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img19_hSign = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img20_iSign = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img21_walker1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img22_walker2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img23_walker3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img24_walker4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img25_trex = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img26_stegosaurus = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img27_triceratop = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img28_globe = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img29_soccerBall = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img30_stop = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img31_go = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img32_check = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img33_x_copy = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img34_no = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img35_left = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img36_right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img37_up = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=background.showImage
    //% tags="background"
    export const img38_down = image.ofBuffer(hex``);
}
